<?php
/**
 * @var $block \Vicomage\General\Block\Adminhtml\System\Config\Color
 */
$baseConfig = $block->getBaseColor();
$headerConfig = $block->getHeaderColor();
$contentConfig = $block->getContentColor();
$footerConfig = $block->getFooterColor();
$footerType2 = $block->getFooterType2();
$footerType3 = $block->getFooterType3();
$footerType4 = $block->getFooterType4();
?>
<?php if ($baseConfig) : ?>
    <?php foreach ($baseConfig as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>


<?php if ($headerConfig) : ?>
    <?php foreach ($headerConfig as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>


<?php if ($contentConfig) : ?>
    <?php foreach ($contentConfig as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($footerConfig) : ?>
    <?php foreach ($footerConfig as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($footerType2) : ?>
    <?php foreach ($footerType2 as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($footerType3) : ?>
    <?php foreach ($footerType3 as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>

<?php if ($footerType4) : ?>
    <?php foreach ($footerType4 as $data): ?>
        <?php if (isset($data['element']) && !empty($data['element'])): ?>
            <?php echo $data['element']; ?>{
            <?php if ($data['color'] != null): ?>
                <?php echo 'color: ' . $data['color'] ?>;
            <?php endif; ?>

            <?php if ($data['bgcolor'] != null): ?>
                <?php echo 'background-color: ' . $data['bgcolor'] ?>;
            <?php endif; ?>

            <?php if ($data['bdcolor'] != null): ?>
                <?php echo 'border-color: ' . $data['bdcolor'] ?>;
            <?php endif; ?>
            }
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>