<?php
    $header_type = $this->getConfig('vicomage_general_config/header/header_type');
?>
<header class="page-header header-type<?php echo $header_type; ?>">
	<?php if($header_type == 1 || $header_type == 3 || $header_type == 4): ?>
    <div class="panel wrapper">
        <div class="panel header header-top">
            
            <?php echo $this->getChildHtml("skip_to_content"); ?>
			<div class="row">
				<div class="header-top-left col-sm-6">
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
				</div>
				<div class="header-top-right col-sm-6">
					<div class="top-links-header switcher" id="links-header">
						<div class="actions dropdown options links-header-options">
							<div class="action toggle links-header-trigger" id="links-header-trigger">
								<strong><?php echo __('My Account') ?></strong>
							</div>
							<div class="links-header-dropdown" data-mage-init='{"dropdownDialog":{
											"appendTo":".links-header-options",
											"triggerTarget":"#links-header-trigger",
											"closeOnMouseLeave": false,
											"triggerClass":"active",
											"parentClass":"active",
											"buttons":null}}'>
								<?php echo $this->getChildHtml("header.links"); ?>
							</div>
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
	<?php endif; ?>
	<?php if($header_type == 1 || $header_type == 2 || $header_type == 3): ?>
    <div class="header-content header-sticker sticker">
		<div class="container">
			<div class="row">
				<div class="col-sm-2 col-md-2 col-lg-2 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-12 header-right">
					<div class="header-content-right">
						<div class="header-content-bottom">
							<div class="header-menu">
								 <?php echo $this->getChildHtml("navigation.sections"); ?>
							</div>
							 <div class="header-top-right">
								
								<div class="header-search">
									<div class="search-switcher">
										<div class="dropdown-toggle">
											<div class="icon-search"><i class="fa fa-search"></i></div>
										</div>
										<div class="dropdown-switcher">
											<?php echo $this->getChildHtml("top.search"); ?>
										</div>
									</div>
								</div>
								<?php if($header_type == 2): ?>
								<div class="header-setting">
									<div class="setting-switcher">
										<div class="dropdown-toggle">
											<div class="icon-setting"><i class="fa fa-cog"></i></div>
										</div>
										<div class="dropdown-switcher">
											<?php echo $this->getChildHtml("header.links"); ?>
											<?php echo $this->getChildHtml("store_language"); ?>
											<?php echo $this->getChildHtml("currency"); ?>
										</div>
									</div>
								</div>
								<?php endif; ?>
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<?php if($header_type == 4): ?>
	<div class="header-content ">
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-md-4 col-lg-4 header-content-left">
					<div class="header-logo">
						 <?php echo $this->getChildHtml("logo_theme"); ?>
					</div>
				</div>
				<div class="col-sm-4 header-center">
					<div class="header-search">
						<div class="search-switcher">
							<div class="dropdown-toggle">
								<div class="icon-search"><i class="fa fa-search"></i></div>
							</div>
							<div class="dropdown-switcher">
								<?php echo $this->getChildHtml("top.search"); ?>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-4 header-right">
					<div class="header-content-right">
						<div class="header-content-bottom">
							 <div class="header-top-right">
								<?php echo $this->getChildHtml("minicart"); ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content-menu header-sticker sticker">
			<div class="container">
				<div class="header-menu">
					<?php echo $this->getChildHtml("navigation.sections"); ?>
				</div>
			</div>
		</div>
	</div>
	
	<?php endif; ?>
</header>