<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$productlimit = $this->getData('product_limit');
$blocktitle = $this->getData('title');
$id = $this->getData('id');
$itemsDesktop = $this->getData('itemsDesktop');
$itemsDesktopSmall = $this->getData('itemsDesktopSmall');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $hover_image = 'category_page_grid-hover';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $pos = $block->getPositioned();
    ?>
    <?php if ($blocktitle) : ?>
        <div class="title-page">
            <h2 class="subtitle"><?php echo $blocktitle ?></h2>
        </div>
    <?php endif; ?>
    <div class="products-custom wrapper <?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items product-items" id="productslide<?php echo $id ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $i = 1;
            foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    /* $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    } */
                    ?>
                    <?php // Product Image ?>
                    <div class="product-img-hover">
                        <a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php

                            $productImage = $_imagehelper->init($_product, $image)->resize(270, 348);
                            $productImageUrl = $productImage->getUrl();
                            ?>
                            <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>"
                                 alt="<?php echo $productImage->getLabel(); ?>"/>

                            <?php
                            $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize(270, 348);
                            $productHoverImageUrl = $productHoverImage->getUrl();
                            ?>
                            <?php if ($productImageUrl != str_replace("/thumbnail/", "/small_image/", $productHoverImageUrl)): ?>
                                <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>"
                                     alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                            <?php endif; ?>
                            <?php // echo $productImage->toHtml(); ?>
                        </a>

                        <div class="product-item-inner">
                            <div
                                class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div
                                    class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                        echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                            echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */
                                            echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                   value="<?php /* @escapeNotVerified */
                                                   echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('View Recipe')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo $block->escapeHtml(__('View Recipe')); ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */
                                                    echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                    echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php /* @escapeNotVerified */
                                                echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php /* @escapeNotVerified */
                                       echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php /* @escapeNotVerified */
                                            echo __('Add to Compare') ?></span>
                                    </a>
                                    <a class="vicomage-quickview btn-quickview"
                                       data-quickview-url="<?php echo $this->getUrl('vicomage_quickview/catalog_product/view/'); ?>id/<?php echo $_product->getId(); ?>"
                                       href="javascript:void(0);"><span><i class="fa fa-search"></i></span></a>

                                </div>
                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                    echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */
                                        echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */
                               echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */
                        echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
                <?php if ($i == $productlimit): ?>
                    <?php break; ?>
                <?php endif ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>
<script type="text/javascript">
    require([
        'jquery',
        'slick'
    ], function ($) {
        $("#productslide<?php echo $id ?>").slick({
            dots: false,
            arrows: true,
            infinite: false,
            speed: 300,
            slidesToShow: <?php  echo $itemsDesktop ?>,
            slidesToScroll: 1,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: <?php echo $itemsDesktop ?>
                    }
                },
                {
                    breakpoint: 991,
                    settings: {
                        slidesToShow: <?php echo $itemsDesktopSmall ?>
                    }
                },
                {
                    breakpoint: 767,
                    settings: {
                        slidesToShow: 3
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 1
                    }
                }
            ]
        });

    });

</script>